using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace HousePlanner.API.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Roles"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" character varying(50) NOT NULL
                );

                INSERT INTO ""Roles"" (""Id"", ""Name"")
                VALUES (1, 'User'), (2, 'Admin')
                ON CONFLICT (""Id"") DO UPDATE SET ""Name"" = EXCLUDED.""Name"";

                CREATE TABLE IF NOT EXISTS ""PreDesignedHousePlans"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""Name"" character varying(160) NOT NULL,
                    ""Slug"" character varying(180) NOT NULL,
                    ""DesignCode"" character varying(50) NOT NULL,
                    ""Description"" character varying(2000),
                    ""Style"" character varying(80) NOT NULL,
                    ""Bedrooms"" integer NOT NULL,
                    ""Bathrooms"" integer NOT NULL,
                    ""FloorCount"" integer NOT NULL,
                    ""TotalBuiltUpAreaSqft"" numeric(10,2) NOT NULL,
                    ""MinimumLandSizePerches"" numeric(10,2) NOT NULL,
                    ""MinimumPlotWidthFt"" numeric(8,2),
                    ""MinimumPlotLengthFt"" numeric(8,2),
                    ""SuitableTerrain"" character varying(30) NOT NULL,
                    ""ParkingSpaces"" integer NOT NULL,
                    ""HasBalcony"" boolean NOT NULL,
                    ""HasVeranda"" boolean NOT NULL,
                    ""HasOffice"" boolean NOT NULL,
                    ""HasUtilityRoom"" boolean NOT NULL,
                    ""IsAccessibleFriendly"" boolean NOT NULL,
                    ""Category"" character varying(80),
                    ""TagsJson"" jsonb NOT NULL,
                    ""ThumbnailUrl"" character varying(500),
                    ""LayoutJson"" jsonb NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_DesignCode"" ON ""PreDesignedHousePlans"" (""DesignCode"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_Slug"" ON ""PreDesignedHousePlans"" (""Slug"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_Bathrooms"" ON ""PreDesignedHousePlans"" (""Bathrooms"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_Bedrooms"" ON ""PreDesignedHousePlans"" (""Bedrooms"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_FloorCount"" ON ""PreDesignedHousePlans"" (""FloorCount"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_IsActive"" ON ""PreDesignedHousePlans"" (""IsActive"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_Style"" ON ""PreDesignedHousePlans"" (""Style"");
                CREATE INDEX IF NOT EXISTS ""IX_PreDesignedHousePlans_SuitableTerrain"" ON ""PreDesignedHousePlans"" (""SuitableTerrain"");

                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""Email"" character varying(255) NOT NULL,
                    ""PasswordHash"" character varying(255) NOT NULL,
                    ""FullName"" character varying(150) NOT NULL,
                    ""RoleId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Roles_RoleId') THEN
                        ALTER TABLE ""Users"" ADD CONSTRAINT ""FK_Users_Roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""Roles"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_Users_RoleId"" ON ""Users"" (""RoleId"");

                CREATE TABLE IF NOT EXISTS ""LandSubmissions"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""ClientId"" uuid NOT NULL,
                    ""BudgetLkr"" numeric(14,2),
                    ""LandSizePerches"" numeric(10,2) NOT NULL,
                    ""LandPhotoUrl"" character varying(500),
                    ""ManualTerrainType"" character varying(30),
                    ""PreferredBedrooms"" integer NOT NULL,
                    ""PreferredFloors"" integer NOT NULL,
                    ""StylePreference"" character varying(50),
                    ""BasePreDesignedPlanId"" uuid,
                    ""PlanSelectionMode"" character varying(20),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );

                ALTER TABLE ""LandSubmissions"" ADD COLUMN IF NOT EXISTS ""BasePreDesignedPlanId"" uuid;
                ALTER TABLE ""LandSubmissions"" ADD COLUMN IF NOT EXISTS ""PlanSelectionMode"" character varying(20);

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LandSubmissions_PreDesignedHousePlans_BasePreDesignedPlanId') THEN
                        ALTER TABLE ""LandSubmissions"" ADD CONSTRAINT ""FK_LandSubmissions_PreDesignedHousePlans_BasePreDesignedPlanId"" FOREIGN KEY (""BasePreDesignedPlanId"") REFERENCES ""PreDesignedHousePlans"" (""Id"") ON DELETE SET NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LandSubmissions_Users_ClientId') THEN
                        ALTER TABLE ""LandSubmissions"" ADD CONSTRAINT ""FK_LandSubmissions_Users_ClientId"" FOREIGN KEY (""ClientId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_LandSubmissions_BasePreDesignedPlanId"" ON ""LandSubmissions"" (""BasePreDesignedPlanId"");
                CREATE INDEX IF NOT EXISTS ""IX_LandSubmissions_ClientId"" ON ""LandSubmissions"" (""ClientId"");

                CREATE TABLE IF NOT EXISTS ""WorkflowStates"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""LandSubmissionId"" uuid NOT NULL,
                    ""Status"" character varying(30) NOT NULL,
                    ""TerrainType"" character varying(30),
                    ""SlopeEstimate"" character varying(30),
                    ""NotableFeatures"" jsonb,
                    ""ConstructionPlan"" jsonb,
                    ""ApprovalStatus"" character varying(30) NOT NULL,
                    ""FailureReason"" character varying(1000),
                    ""ApprovedByUserId"" uuid,
                    ""ApprovedAt"" timestamp with time zone,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WorkflowStates_LandSubmissions_LandSubmissionId') THEN
                        ALTER TABLE ""WorkflowStates"" ADD CONSTRAINT ""FK_WorkflowStates_LandSubmissions_LandSubmissionId"" FOREIGN KEY (""LandSubmissionId"") REFERENCES ""LandSubmissions"" (""Id"") ON DELETE CASCADE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WorkflowStates_Users_ApprovedByUserId') THEN
                        ALTER TABLE ""WorkflowStates"" ADD CONSTRAINT ""FK_WorkflowStates_Users_ApprovedByUserId"" FOREIGN KEY (""ApprovedByUserId"") REFERENCES ""Users"" (""Id"");
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_WorkflowStates_ApprovedByUserId"" ON ""WorkflowStates"" (""ApprovedByUserId"");
                CREATE INDEX IF NOT EXISTS ""IX_WorkflowStates_LandSubmissionId"" ON ""WorkflowStates"" (""LandSubmissionId"");

                CREATE TABLE IF NOT EXISTS ""HouseDesigns"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""WorkflowStateId"" uuid NOT NULL,
                    ""Version"" integer NOT NULL,
                    ""FloorCount"" integer NOT NULL,
                    ""TotalBuiltUpAreaSqft"" numeric(10,2) NOT NULL,
                    ""FoundationType"" character varying(30) NOT NULL,
                    ""TemplateId"" character varying(50),
                    ""TerrainType"" character varying(30),
                    ""IsCurrent"" boolean NOT NULL,
                    ""LayoutJson"" jsonb NOT NULL,
                    ""DesignSource"" character varying(30) NOT NULL DEFAULT 'ai_generated',
                    ""BasePreDesignedPlanId"" uuid,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now()
                );

                ALTER TABLE ""HouseDesigns"" ADD COLUMN IF NOT EXISTS ""BasePreDesignedPlanId"" uuid;
                ALTER TABLE ""HouseDesigns"" ADD COLUMN IF NOT EXISTS ""DesignSource"" character varying(30) NOT NULL DEFAULT 'ai_generated';

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_HouseDesigns_PreDesignedHousePlans_BasePreDesignedPlanId') THEN
                        ALTER TABLE ""HouseDesigns"" ADD CONSTRAINT ""FK_HouseDesigns_PreDesignedHousePlans_BasePreDesignedPlanId"" FOREIGN KEY (""BasePreDesignedPlanId"") REFERENCES ""PreDesignedHousePlans"" (""Id"") ON DELETE SET NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_HouseDesigns_WorkflowStates_WorkflowStateId') THEN
                        ALTER TABLE ""HouseDesigns"" ADD CONSTRAINT ""FK_HouseDesigns_WorkflowStates_WorkflowStateId"" FOREIGN KEY (""WorkflowStateId"") REFERENCES ""WorkflowStates"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_HouseDesigns_BasePreDesignedPlanId"" ON ""HouseDesigns"" (""BasePreDesignedPlanId"");
                CREATE INDEX IF NOT EXISTS ""IX_HouseDesigns_WorkflowState_IsCurrent"" ON ""HouseDesigns"" (""WorkflowStateId"", ""IsCurrent"");
                CREATE INDEX IF NOT EXISTS ""IX_HouseDesigns_WorkflowStateId"" ON ""HouseDesigns"" (""WorkflowStateId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""UX_HouseDesigns_WorkflowState_Version"" ON ""HouseDesigns"" (""WorkflowStateId"", ""Version"");

                CREATE TABLE IF NOT EXISTS ""Rooms"" (
                    ""Id"" uuid NOT NULL PRIMARY KEY,
                    ""HouseDesignId"" uuid NOT NULL,
                    ""RoomType"" character varying(50) NOT NULL,
                    ""Name"" character varying(100),
                    ""X"" numeric(8,2) NOT NULL,
                    ""Y"" numeric(8,2) NOT NULL,
                    ""Width"" numeric(8,2) NOT NULL,
                    ""Length"" numeric(8,2) NOT NULL,
                    ""AreaSqft"" numeric(10,2) NOT NULL,
                    ""WallHeight"" numeric(6,2) NOT NULL,
                    ""FloorNumber"" integer NOT NULL
                );

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Rooms_HouseDesigns_HouseDesignId') THEN
                        ALTER TABLE ""Rooms"" ADD CONSTRAINT ""FK_Rooms_HouseDesigns_HouseDesignId"" FOREIGN KEY (""HouseDesignId"") REFERENCES ""HouseDesigns"" (""Id"") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_Rooms_HouseDesignId"" ON ""Rooms"" (""HouseDesignId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Rooms");

            migrationBuilder.DropTable(
                name: "HouseDesigns");

            migrationBuilder.DropTable(
                name: "WorkflowStates");

            migrationBuilder.DropTable(
                name: "LandSubmissions");

            migrationBuilder.DropTable(
                name: "PreDesignedHousePlans");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "Roles");
        }
    }
}
