// <auto-generated />
using System;
using HousePlanner.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HousePlanner.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920083349_AddFirebaseApplicationUserMapping")]
    partial class AddFirebaseApplicationUserMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedDurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructionPhases");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorWorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("Challenges")
                        .HasColumnType("text");

                    b.Property<string>("CompletedWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConstructionPhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Issues")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TomorrowPlan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionPhaseId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructorWorkflowLogs");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetDeltaPercent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LabourCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("MaterialCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TotalCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId")
                        .IsUnique()
                        .HasDatabaseName("IX_CostEstimates_HouseDesignId");

                    b.ToTable("CostEstimates");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasePreDesignedPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DesignSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FoundationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalBuiltUpAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BasePreDesignedPlanId");

                    b.HasIndex("WorkflowStateId")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowStateId");

                    b.HasIndex("WorkflowStateId", "IsArchived")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowState_IsArchived");

                    b.HasIndex("WorkflowStateId", "IsCurrent")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowState_IsCurrent");

                    b.HasIndex("WorkflowStateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_HouseDesigns_WorkflowState_Version");

                    b.ToTable("HouseDesigns");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.LandSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasePreDesignedPlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BudgetLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LandPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("LandSizePerches")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ManualTerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PlanSelectionMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PreferredBedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredFloors")
                        .HasColumnType("integer");

                    b.Property<string>("StylePreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BasePreDesignedPlanId");

                    b.HasIndex("ClientId");

                    b.ToTable("LandSubmissions");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PreDesignedHousePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DesignCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMasterEnsuite")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOffice")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOpenPlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeparateDining")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUtilityRoom")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVeranda")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAccessibleFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MinimumLandSizePerches")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinimumPlotLengthFt")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MinimumPlotWidthFt")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SuitableTerrain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("TotalBuiltUpAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Bathrooms");

                    b.HasIndex("Bedrooms");

                    b.HasIndex("DesignCode")
                        .IsUnique();

                    b.HasIndex("FloorCount");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Style");

                    b.HasIndex("SuitableTerrain");

                    b.ToTable("PreDesignedHousePlans");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitCostLkr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PricingData");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("WorkflowStateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("WallHeight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId")
                        .HasDatabaseName("IX_Rooms_HouseDesignId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_FirebaseUid");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ValidationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchitectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchitectReview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkflowStateId");

                    b.ToTable("ValidationRequests");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstructionPlan")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LandSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotableFeatures")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PreferredHouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlopeEstimate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("LandSubmissionId");

                    b.HasIndex("PreferredHouseDesignId")
                        .HasDatabaseName("IX_WorkflowStates_PreferredHouseDesignId");

                    b.ToTable("WorkflowStates");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionPhase", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany("ConstructionPhases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorWorkflowLog", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.ConstructionPhase", "ConstructionPhase")
                        .WithMany()
                        .HasForeignKey("ConstructionPhaseId");

                    b.HasOne("HousePlanner.API.Entities.User", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionPhase");

                    b.Navigation("Constructor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimate", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany("CostEstimates")
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseDesign");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.PreDesignedHousePlan", "BasePreDesignedPlan")
                        .WithMany("DerivedDesigns")
                        .HasForeignKey("BasePreDesignedPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany("HouseDesigns")
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePreDesignedPlan");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.LandSubmission", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.PreDesignedHousePlan", "BasePreDesignedPlan")
                        .WithMany()
                        .HasForeignKey("BasePreDesignedPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HousePlanner.API.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePreDesignedPlan");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingData", b =>
                {
                    b.OwnsOne("HousePlanner.API.Entities.TerrainMultiplierData", "TerrainMultiplier", b1 =>
                        {
                            b1.Property<int>("PricingDataId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Coastal")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "coastal");

                            b1.Property<decimal>("Flat")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "flat");

                            b1.Property<decimal>("Hillside")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "hillside");

                            b1.HasKey("PricingDataId");

                            b1.ToTable("PricingData");

                            b1.ToJson("TerrainMultiplier");

                            b1.WithOwner()
                                .HasForeignKey("PricingDataId");
                        });

                    b.Navigation("TerrainMultiplier")
                        .IsRequired();
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId");

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Room", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany("Rooms")
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseDesign");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.User", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ValidationRequest", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "Architect")
                        .WithMany()
                        .HasForeignKey("ArchitectId");

                    b.HasOne("HousePlanner.API.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architect");

                    b.Navigation("Client");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("HousePlanner.API.Entities.LandSubmission", "LandSubmission")
                        .WithMany()
                        .HasForeignKey("LandSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.HouseDesign", null)
                        .WithMany()
                        .HasForeignKey("PreferredHouseDesignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("LandSubmission");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.Navigation("CostEstimates");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PreDesignedHousePlan", b =>
                {
                    b.Navigation("DerivedDesigns");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.Navigation("ConstructionPhases");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.Navigation("HouseDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
