import { useCallback, useEffect, useState } from 'react';
import { UserPlus, X } from 'lucide-react';
import { staffService, type CreateStaffRequest, type StaffAccount, type StaffRole, type UpdateStaffRequest } from '../services/staffService';

type Filter = 'All' | 'Architect' | 'Constructor';
const empty:CreateStaffRequest={fullName:'',email:'',password:'',role:'Architect'};

export default function AdminStaffPage(){
 const [staff,setStaff]=useState<StaffAccount[]>([]),[filter,setFilter]=useState<Filter>('All'),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [editing,setEditing]=useState<StaffAccount|null>(null),[editForm,setEditForm]=useState<UpdateStaffRequest>({fullName:'',email:'',role:'Architect'}),[success,setSuccess]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{setStaff(await staffService.list(filter==='All'?undefined:filter));setError('')}catch(ex:unknown){const status=(ex as {response?:{status?:number}})?.response?.status;if(status===401)setError('Your session has expired. Please sign in again.');else if(status===403)setError('You do not have permission to manage staff accounts.');else setError('Could not load staff accounts.')}finally{setLoading(false)}},[filter]);
 useEffect(()=>{void load()},[load]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(form.password.length<6)return setError('Password must be at least 6 characters.');if(form.password!==confirm)return setError('Passwords do not match.');try{await staffService.create(form);setOpen(false);setForm(empty);setConfirm('');await load()}catch(ex:any){setError(ex.response?.data?.message||'Staff account could not be created.')}};
 const toggle=async(person:StaffAccount)=>{try{await staffService.setDisabled(person.id,person.status!=='Disabled');await load()}catch{setError('Staff account status could not be updated.')}};
 const beginEdit=(person:StaffAccount)=>{setEditing(person);setEditForm({fullName:person.fullName,email:person.email,role:person.role});setError('');setSuccess('')};
 const saveEdit=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;setError('');try{await staffService.update(editing.id,editForm);setEditing(null);setSuccess('Staff account updated.');await load()}catch(ex:any){setError(ex.response?.data?.message||'Staff account could not be updated.')}};
 return <main className="p-6 md:p-10 max-w-6xl mx-auto text-zinc-900 dark:text-white"><div className="flex flex-wrap justify-between gap-4 items-end"><div><p className="text-indigo-600 text-sm font-semibold">ADMIN</p><h1 className="text-3xl font-bold">Staff Management</h1><p className="text-zinc-500 mt-2">Manage Architect and Constructor accounts.</p></div><button onClick={()=>{setOpen(true);setError('')}} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-semibold flex gap-2"><UserPlus size={18}/>Add Staff Member</button></div>
 <div className="my-6 flex w-full flex-col gap-1 rounded-xl border border-slate-700 bg-slate-950 p-1 sm:inline-flex sm:w-auto sm:flex-row" role="group" aria-label="Staff role filter">{(['All','Architect','Constructor'] as Filter[]).map(value=>{const active=filter===value;return <button type="button" key={value} aria-pressed={active} onClick={()=>setFilter(value)} className={`min-h-10 rounded-lg border px-4 py-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 ${active?'border-indigo-500 bg-indigo-600 text-white shadow-sm shadow-indigo-950/40':'border-slate-700 bg-slate-900 text-slate-300 hover:border-slate-600 hover:bg-slate-800 hover:text-white'}`}>{value==='Architect'?'Architects':value==='Constructor'?'Constructors':value}</button>})}</div>
 {success&&<p role="status" className="p-3 bg-emerald-50 text-emerald-700 rounded-xl mb-4">{success}</p>}{error&&!open&&!editing&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-xl mb-4">{error}</p>}{loading?<p>Loading staff…</p>:<div className="overflow-x-auto rounded-2xl border"><table className="w-full bg-white dark:bg-gray-900 text-sm"><thead className="bg-zinc-50 dark:bg-gray-800 text-left"><tr><th className="p-4">Name</th><th>Email</th><th>Role</th><th>Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{staff.map(person=><tr key={person.id} className="border-t"><td className="p-4 font-semibold">{person.fullName}</td><td>{person.email}</td><td>{person.role}</td><td><span className={person.status==='Active'?'text-emerald-700':'text-zinc-500'}>{person.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button type="button" onClick={()=>beginEdit(person)} className="rounded-lg border border-slate-600 px-3 py-1.5 text-sm hover:bg-slate-800 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Edit</button><button disabled={person.status==='Unavailable'} onClick={()=>toggle(person)} className="border px-3 py-1.5 rounded-lg disabled:opacity-40">{person.status==='Disabled'?'Enable':'Disable'}</button></div></td></tr>)}</tbody></table>{!staff.length&&<p className="p-10 text-center text-zinc-500">No staff accounts found.</p>}</div>}
 {open&&<div role="dialog" aria-modal="true" aria-label="Add Staff Member" className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form onSubmit={create} className="w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Add Staff Member</h2><p className="text-sm text-zinc-500">Create secure Firebase login credentials and a staff profile.</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}><X/></button></div>{error&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-xl my-4">{error}</p>}<div className="grid gap-4 mt-5"><label>Full Name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as StaffRole})} className="block w-full mt-1 p-3 border rounded-xl"><option>Architect</option><option>Constructor</option></select></label><label>Password<input required minLength={6} type="password" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Confirm Password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="block w-full mt-1 p-3 border rounded-xl"/></label><button className="bg-indigo-600 text-white py-3 rounded-xl font-semibold">Create Staff Account</button></div></form></div>}
 {editing&&<div role="dialog" aria-modal="true" aria-label="Edit Staff Member" className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form onSubmit={saveEdit} className="w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Edit Staff Member</h2><p className="text-sm text-zinc-500">Update the staff profile and Firebase sign-in email.</p></div><button type="button" aria-label="Close" onClick={()=>{setEditing(null);setError('')}}><X/></button></div>{error&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-xl my-4">{error}</p>}<div className="grid gap-4 mt-5"><label>Full Name<input required value={editForm.fullName} onChange={e=>setEditForm({...editForm,fullName:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Email<input required type="email" value={editForm.email} onChange={e=>setEditForm({...editForm,email:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Role<select value={editForm.role} onChange={e=>setEditForm({...editForm,role:e.target.value as StaffRole})} className="block w-full mt-1 p-3 border rounded-xl"><option>Architect</option><option>Constructor</option></select></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>{setEditing(null);setError('')}} className="px-4 py-2.5 rounded-xl border">Cancel</button><button className="px-4 py-2.5 rounded-xl bg-indigo-600 text-white font-semibold">Save Changes</button></div></div></form></div>}
 </main>
}
