import { useEffect, useState } from 'react';
import { UserPlus, X } from 'lucide-react';
import { staffService, type CreateStaffRequest, type StaffAccount, type StaffRole } from '../services/staffService';

type Filter = 'All' | 'Architect' | 'Constructor';
const empty:CreateStaffRequest={fullName:'',email:'',password:'',role:'Architect'};

export default function AdminStaffPage(){
 const [staff,setStaff]=useState<StaffAccount[]>([]),[filter,setFilter]=useState<Filter>('All'),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setStaff(await staffService.list(filter==='All'?undefined:filter));setError('')}catch(ex:unknown){const status=(ex as {response?:{status?:number}})?.response?.status;if(status===401)setError('Your session has expired. Please sign in again.');else if(status===403)setError('You do not have permission to manage staff accounts.');else setError('Could not load staff accounts.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[filter]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(form.password.length<6)return setError('Password must be at least 6 characters.');if(form.password!==confirm)return setError('Passwords do not match.');try{await staffService.create(form);setOpen(false);setForm(empty);setConfirm('');await load()}catch(ex:any){setError(ex.response?.data?.message||'Staff account could not be created.')}};
 const toggle=async(person:StaffAccount)=>{try{await staffService.setDisabled(person.id,person.status!=='Disabled');await load()}catch{setError('Staff account status could not be updated.')}};
 return <main className="p-6 md:p-10 max-w-6xl mx-auto text-zinc-900 dark:text-white"><div className="flex flex-wrap justify-between gap-4 items-end"><div><p className="text-indigo-600 text-sm font-semibold">ADMIN</p><h1 className="text-3xl font-bold">Staff Management</h1><p className="text-zinc-500 mt-2">Manage Architect and Constructor accounts.</p></div><button onClick={()=>{setOpen(true);setError('')}} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-semibold flex gap-2"><UserPlus size={18}/>Add Staff Member</button></div>
 <div className="flex gap-2 my-6" aria-label="Staff role filter">{(['All','Architect','Constructor'] as Filter[]).map(value=><button key={value} onClick={()=>setFilter(value)} className={`px-4 py-2 rounded-full text-sm font-semibold ${filter===value?'bg-zinc-900 text-white':'bg-white border'}`}>{value==='Architect'?'Architects':value==='Constructor'?'Constructors':value}</button>)}</div>
 {error&&!open&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-xl mb-4">{error}</p>}{loading?<p>Loading staff…</p>:<div className="overflow-x-auto rounded-2xl border"><table className="w-full bg-white dark:bg-gray-900 text-sm"><thead className="bg-zinc-50 dark:bg-gray-800 text-left"><tr><th className="p-4">Name</th><th>Email</th><th>Role</th><th>Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{staff.map(person=><tr key={person.id} className="border-t"><td className="p-4 font-semibold">{person.fullName}</td><td>{person.email}</td><td>{person.role}</td><td><span className={person.status==='Active'?'text-emerald-700':'text-zinc-500'}>{person.status}</span></td><td className="p-4 text-right"><button disabled={person.status==='Unavailable'} onClick={()=>toggle(person)} className="border px-3 py-1.5 rounded-lg disabled:opacity-40">{person.status==='Disabled'?'Enable':'Disable'}</button></td></tr>)}</tbody></table>{!staff.length&&<p className="p-10 text-center text-zinc-500">No staff accounts found.</p>}</div>}
 {open&&<div role="dialog" aria-modal="true" aria-label="Add Staff Member" className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form onSubmit={create} className="w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Add Staff Member</h2><p className="text-sm text-zinc-500">Create secure Firebase login credentials and a staff profile.</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}><X/></button></div>{error&&<p role="alert" className="p-3 bg-red-50 text-red-700 rounded-xl my-4">{error}</p>}<div className="grid gap-4 mt-5"><label>Full Name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as StaffRole})} className="block w-full mt-1 p-3 border rounded-xl"><option>Architect</option><option>Constructor</option></select></label><label>Password<input required minLength={6} type="password" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="block w-full mt-1 p-3 border rounded-xl"/></label><label>Confirm Password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="block w-full mt-1 p-3 border rounded-xl"/></label><button className="bg-indigo-600 text-white py-3 rounded-xl font-semibold">Create Staff Account</button></div></form></div>}
 </main>
}
