import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { FloorPlanViewer, type FloorPlanData } from '../components/floorplan/FloorPlanViewer';
import { preDesignedPlanService, type SavePlan } from '../services/preDesignedPlanService';

const blank:any={name:'',slug:'',designCode:'',description:'',style:'modern',bedrooms:2,bathrooms:1,floorCount:1,totalBuiltUpAreaSqft:700,minimumLandSizePerches:8,suitableTerrain:'flat',parkingSpaces:0,hasBalcony:false,hasVeranda:false,hasOffice:false,hasUtilityRoom:false,isAccessibleFriendly:false,category:'Starter',tags:[],isActive:true,layout:{design_id:crypto.randomUUID(),floor_count:1,total_built_up_area_sqft:700,rooms:[]}};
export default function AdminPlanFormPage(){
 const {id}=useParams(),nav=useNavigate(); const [form,setForm]=useState<any>(blank),[layoutText,setLayoutText]=useState(JSON.stringify(blank.layout,null,2)),[preview,setPreview]=useState<FloorPlanData>(),[error,setError]=useState('');
 useEffect(()=>{if(id)preDesignedPlanService.adminDetail(id).then(p=>{setForm(p);setLayoutText(JSON.stringify(p.layout,null,2));setPreview(p.layout)}).catch(()=>setError('Plan could not be loaded.'));},[id]);
 const change=(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>{const {name,value}=e.target;setForm((x:any)=>({...x,[name]:e.target instanceof HTMLInputElement&&e.target.type==='checkbox'?e.target.checked:e.target instanceof HTMLInputElement&&e.target.type==='number'?Number(value):value}));};
 const parse=()=>{try{const x=JSON.parse(layoutText);setPreview(x);setError('');return x}catch{setError('Layout JSON is invalid.');return null}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();const layout=parse();if(!layout)return;try{const payload={...form,layout,tags:typeof form.tags==='string'?form.tags.split(',').map((x:string)=>x.trim()).filter(Boolean):form.tags} as SavePlan;if(id)await preDesignedPlanService.update(id,payload);else await preDesignedPlanService.create(payload);nav('/dashboard/admin/plans')}catch(ex:any){setError(ex.response?.data?.errors?.join(' ')||'The plan could not be saved.')}};
 const inputs=[['name','Name','text'],['slug','Slug','text'],['designCode','Design code','text'],['style','Style','text'],['bedrooms','Bedrooms','number'],['bathrooms','Bathrooms','number'],['floorCount','Floors','number'],['totalBuiltUpAreaSqft','Built-up area (ft²)','number'],['minimumLandSizePerches','Minimum land (perches)','number'],['minimumPlotWidthFt','Minimum plot width (ft)','number'],['minimumPlotLengthFt','Minimum plot length (ft)','number'],['parkingSpaces','Parking spaces','number'],['category','Category','text']];
 return <main className="p-6 md:p-10 max-w-7xl mx-auto text-zinc-900 dark:text-white"><h1 className="text-3xl font-bold mb-6">{id?'Edit':'Add'} pre-designed plan</h1>{error&&<p role="alert" className="bg-red-50 text-red-700 p-3 rounded-xl mb-4">{error}</p>}<form onSubmit={save} className="grid lg:grid-cols-2 gap-6"><section className="bg-white dark:bg-gray-900 border rounded-2xl p-5 grid sm:grid-cols-2 gap-4">{inputs.map(([name,label,type])=><label key={name} className="text-sm">{label}<input required={!['minimumPlotWidthFt','minimumPlotLengthFt'].includes(name)} name={name} type={type} value={form[name]??''} onChange={change} className="block w-full mt-1 p-2.5 rounded-lg bg-zinc-50 dark:bg-gray-950 border"/></label>)}<label className="text-sm">Terrain<select name="suitableTerrain" value={form.suitableTerrain} onChange={change} className="block w-full mt-1 p-2.5 rounded-lg bg-zinc-50 dark:bg-gray-950 border">{['flat','urban','hillside','coastal','all'].map(x=><option key={x}>{x}</option>)}</select></label><label className="sm:col-span-2 text-sm">Description<textarea name="description" value={form.description??''} onChange={change} className="block w-full mt-1 p-2.5 rounded-lg bg-zinc-50 dark:bg-gray-950 border"/></label><label className="sm:col-span-2 text-sm">Tags (comma separated)<input name="tags" value={Array.isArray(form.tags)?form.tags.join(', '):form.tags} onChange={change} className="block w-full mt-1 p-2.5 rounded-lg bg-zinc-50 dark:bg-gray-950 border"/></label><div className="sm:col-span-2 flex flex-wrap gap-4">{[['hasBalcony','Balcony'],['hasVeranda','Veranda'],['hasOffice','Office'],['hasUtilityRoom','Utility'],['isAccessibleFriendly','Accessible'],['isActive','Active']].map(([n,l])=><label key={n}><input name={n} type="checkbox" checked={!!form[n]} onChange={change}/> {l}</label>)}</div></section><section><label className="text-sm">Layout JSON<textarea value={layoutText} onChange={e=>setLayoutText(e.target.value)} onBlur={parse} className="font-mono text-xs w-full h-72 p-3 rounded-xl bg-gray-950 text-emerald-300"/></label><button type="button" onClick={parse} className="border px-4 py-2 rounded-lg my-3">Validate preview</button><div className="h-80 border rounded-xl overflow-hidden">{preview?.rooms?.length?<FloorPlanViewer data={preview}/>:<div className="h-full grid place-items-center text-zinc-400">Add valid rooms to preview</div>}</div></section><div className="lg:col-span-2 flex justify-end gap-3"><button type="button" onClick={()=>nav('/dashboard/admin/plans')} className="border px-5 py-3 rounded-xl">Cancel</button><button className="bg-indigo-600 text-white px-5 py-3 rounded-xl">Save plan</button></div></form></main>
}
