import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { FloorPlanViewer } from '../components/floorplan/FloorPlanViewer';
import { preDesignedPlanService, type PreDesignedPlanDetail, type PlanCompatibility } from '../services/preDesignedPlanService';

export default function PlanDetailPage(){
 const {id=''}=useParams(), navigate=useNavigate(); const [plan,setPlan]=useState<PreDesignedPlanDetail>(),[floor,setFloor]=useState(1),[result,setResult]=useState<PlanCompatibility>(),[error,setError]=useState('');
 useEffect(()=>{preDesignedPlanService.detail(id).then(setPlan).catch(()=>setError('Plan not found or unavailable.'));},[id]);
 if(error)return <div role="alert" className="p-10">{error} <Link className="text-indigo-500" to="/dashboard/plans">Back to library</Link></div>; if(!plan)return <p className="p-10">Loading plan…</p>;
 const check=async()=>setResult(await preDesignedPlanService.compatibility(id,{landSizePerches:plan.minimumLandSizePerches,plotWidthFt:plan.minimumPlotWidthFt,plotLengthFt:plan.minimumPlotLengthFt,terrain:plan.suitableTerrain,preferredBedrooms:plan.bedrooms,preferredFloors:plan.floorCount}));
 return <main className="p-6 md:p-10 max-w-7xl mx-auto text-zinc-900 dark:text-white"><Link className="text-indigo-500" to="/dashboard/plans">← Plan library</Link><div className="flex flex-wrap justify-between items-end gap-4 my-6"><div><p className="font-mono text-indigo-500">{plan.designCode}</p><h1 className="text-3xl font-bold">{plan.name}</h1><p className="text-zinc-500 mt-2 max-w-2xl">{plan.description}</p></div><div className="flex gap-2"><button onClick={check} className="border px-4 py-3 rounded-xl">Check compatibility</button><button onClick={()=>navigate(`/dashboard/new-project?basePlanId=${id}&mode=use`)} className="bg-indigo-600 text-white px-4 py-3 rounded-xl">Use this plan</button><button onClick={()=>navigate(`/dashboard/new-project?basePlanId=${id}&mode=adapt`)} className="bg-zinc-900 text-white px-4 py-3 rounded-xl">Adapt this plan</button></div></div>
 {result&&<div className={`mb-5 p-4 rounded-xl ${result.compatible?'bg-emerald-100 text-emerald-900':'bg-amber-100 text-amber-900'}`}><b>{result.compatible?'Compatible with these details':'Review compatibility'}</b>{[...result.issues,...result.warnings].map(x=><p key={x}>{x}</p>)}</div>}
 <div className="grid lg:grid-cols-[1fr_300px] gap-6"><section className="h-[620px] rounded-2xl overflow-hidden border border-zinc-200"><div className="absolute z-10 m-3 flex gap-2">{Array.from({length:plan.floorCount},(_,i)=><button key={i} onClick={()=>setFloor(i+1)} className={`px-3 py-1 rounded-lg ${floor===i+1?'bg-indigo-600 text-white':'bg-white'}`}>Floor {i+1}</button>)}</div><FloorPlanViewer data={plan.layout} floorFilter={floor}/></section><aside className="bg-white dark:bg-gray-900 border rounded-2xl p-5 h-fit"><h2 className="font-bold mb-4">Plan facts</h2>{[['Bedrooms',plan.bedrooms],['Bathrooms',plan.bathrooms],['Floors',plan.floorCount],['Built-up area',`${plan.totalBuiltUpAreaSqft} ft²`],['Minimum land',`${plan.minimumLandSizePerches} perches`],['Minimum plot',`${plan.minimumPlotWidthFt??'—'} × ${plan.minimumPlotLengthFt??'—'} ft`],['Terrain',plan.suitableTerrain],['Parking',plan.parkingSpaces]].map(([k,v])=><div key={k} className="flex justify-between border-b py-2 text-sm"><span className="text-zinc-500">{k}</span><b className="capitalize">{v}</b></div>)}</aside></div><p className="mt-5 text-sm text-amber-700 bg-amber-50 p-4 rounded-xl">{plan.conceptualDisclaimer}</p></main>
}
