import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bath, BedDouble, House, Layers3, Ruler, Search } from 'lucide-react';
import { preDesignedPlanService, type PlanFilters, type PreDesignedPlanSummary } from '../services/preDesignedPlanService';
import { countLabel, formatArea, formatTerrain, formatTopology, getCustomerPlanName, getPlanTopology } from '../utils/presentation';

export default function PlanLibraryPage(){
 const [plans,setPlans]=useState<PreDesignedPlanSummary[]>([]), [filters,setFilters]=useState<PlanFilters>({}), [loading,setLoading]=useState(true), [error,setError]=useState('');
 useEffect(()=>{setLoading(true); preDesignedPlanService.list(filters).then(setPlans).catch(()=>setError('Could not load the plan library.')).finally(()=>setLoading(false));},[filters]);
 const field=(key:keyof PlanFilters,value:string)=>setFilters(f=>({...f,[key]:value===''?undefined:['bedrooms','bathrooms','floors','minimumLandSizePerches','maximumBuiltUpArea'].includes(key)?Number(value):value}));
 return <main className="p-6 md:p-10 max-w-7xl mx-auto text-zinc-900 dark:text-text-primary">
 <div className="mb-8"><p className="text-indigo-600 font-semibold text-sm">HOME DESIGN COLLECTION</p><h1 className="text-3xl font-bold mt-1">House Plan Library</h1><p className="text-text-secondary dark:text-zinc-300 mt-2">Explore professionally prepared home layouts and choose a plan that matches your needs.</p></div>
 <div className="grid md:grid-cols-4 gap-3 mb-8 bg-surface p-4 rounded-2xl border border-border dark:border-border-strong">
  <label className="relative md:col-span-2"><Search className="absolute left-3 top-3 text-text-secondary" size={18}/><input aria-label="Search plans" className="w-full pl-10 p-2.5 rounded-xl bg-surface-elevated bg-background border border-border" placeholder="Search name, style or tag" onChange={e=>field('search',e.target.value)}/></label>
  <select aria-label="Bedrooms" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" onChange={e=>field('bedrooms',e.target.value)}><option value="">Any bedrooms</option>{[2,3,4].map(x=><option key={x}>{x}</option>)}</select>
  <select aria-label="Floors" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" onChange={e=>field('floors',e.target.value)}><option value="">Any floors</option><option>1</option><option>2</option></select>
  <select aria-label="Bathrooms" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" onChange={e=>field('bathrooms',e.target.value)}><option value="">Any bathrooms</option>{[1,2,3].map(x=><option key={x}>{x}</option>)}</select>
  <input aria-label="Style" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" placeholder="Style" onChange={e=>field('style',e.target.value)}/>
  <select aria-label="Terrain" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" onChange={e=>field('terrain',e.target.value)}><option value="">Any terrain</option>{['flat','urban','hillside','coastal'].map(x=><option key={x} value={x}>{formatTerrain(x)}</option>)}</select>
  <input aria-label="Maximum land perches" type="number" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" placeholder="Available land (perches)" onChange={e=>field('minimumLandSizePerches',e.target.value)}/>
  <input aria-label="Maximum built-up area" type="number" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" placeholder="Max built-up area (ft²)" onChange={e=>field('maximumBuiltUpArea',e.target.value)}/>
  <input aria-label="Category" className="p-2.5 rounded-xl bg-surface-elevated bg-background border" placeholder="Category" onChange={e=>field('category',e.target.value)}/>
  <label className="flex items-center gap-2 px-2"><input type="checkbox" onChange={e=>setFilters(f=>({...f,parking:e.target.checked||undefined}))}/> Parking</label><label className="flex items-center gap-2 px-2"><input type="checkbox" onChange={e=>setFilters(f=>({...f,office:e.target.checked||undefined}))}/> Office</label><label className="flex items-center gap-2 px-2"><input type="checkbox" onChange={e=>setFilters(f=>({...f,balcony:e.target.checked||undefined}))}/> Balcony</label><label className="flex items-center gap-2 px-2"><input type="checkbox" onChange={e=>setFilters(f=>({...f,accessible:e.target.checked||undefined}))}/> Accessible</label>
 </div>
 {loading?<p>Loading plans…</p>:error?<p role="alert">{error}</p>:plans.length===0?<div className="p-12 text-center border border-dashed rounded-2xl">No plans match these filters.</div>:<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{plans.map(p=>{const topology=getPlanTopology(p); return <Link aria-label={`View ${getCustomerPlanName(p)}`} key={p.id} to={`/dashboard/plans/${p.id}`} className="group bg-surface border border-border dark:border-border-strong rounded-2xl overflow-hidden hover:border-indigo-400 hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-indigo-300 transition">
  <div className="h-36 bg-gradient-to-br from-indigo-50 via-white to-emerald-50 dark:from-indigo-950 dark:via-gray-900 dark:to-emerald-950 flex flex-col items-center justify-center gap-2 text-center"><House aria-hidden="true" className="text-indigo-600" size={34}/><strong className="text-zinc-800 dark:text-zinc-100">{countLabel(p.bedrooms,'Bedroom')}</strong><span className="text-sm text-text-muted dark:text-zinc-300">{countLabel(p.floorCount,'Floor')}</span>{topology&&<span className="text-xs font-semibold text-indigo-700 dark:text-indigo-300">{formatTopology(topology)}</span>}</div>
  <div className="p-5"><h2 className="font-bold text-xl text-zinc-900 dark:text-text-primary">{getCustomerPlanName(p)}</h2><p className="text-sm text-text-muted dark:text-zinc-300 capitalize mt-1">{p.style}</p><div className="grid grid-cols-2 gap-3 mt-5 text-sm text-zinc-700 dark:text-gray-200"><span className="flex items-center gap-2"><BedDouble aria-hidden="true" size={18}/>{countLabel(p.bedrooms,'Bedroom')}</span><span className="flex items-center gap-2"><Bath aria-hidden="true" size={18}/>{countLabel(p.bathrooms,'Bathroom')}</span><span className="flex items-center gap-2"><Layers3 aria-hidden="true" size={18}/>{countLabel(p.floorCount,'Floor')}</span><span className="flex items-center gap-2"><Ruler aria-hidden="true" size={18}/>{formatArea(p.totalBuiltUpAreaSqft)}</span></div><div className="mt-5 pt-4 border-t border-zinc-100 border-border-strong flex items-center justify-between"><span className="text-sm text-text-muted">{topology?formatTopology(topology):formatTerrain(p.suitableTerrain)}</span><span className="font-semibold text-indigo-600 group-hover:underline">View Plan</span></div></div>
 </Link>})}</div>}
 </main>
}
