import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { FloorPlanViewer } from '../components/floorplan/FloorPlanViewer';
import { preDesignedPlanService, type PreDesignedPlanDetail, type PlanCompatibility } from '../services/preDesignedPlanService';
import { countLabel, formatArea, formatFloorName, formatTerrain, formatTopology, getCustomerPlanName, getPlanTopology } from '../utils/presentation';

export default function PlanDetailPage(){
 const {id=''}=useParams(), navigate=useNavigate(); const [plan,setPlan]=useState<PreDesignedPlanDetail>(),[floor,setFloor]=useState(1),[result,setResult]=useState<PlanCompatibility>(),[error,setError]=useState(''),[actionError,setActionError]=useState(''),[checking,setChecking]=useState(false),[needsProject,setNeedsProject]=useState(false),[starting,setStarting]=useState(false);
 useEffect(()=>{preDesignedPlanService.detail(id).then(setPlan).catch(()=>setError('Plan not found or unavailable.'));},[id]);
 if(error)return <div role="alert" className="p-10">{error} <Link className="text-indigo-500" to="/dashboard/plans">Back to library</Link></div>; if(!plan)return <p className="p-10">Loading plan…</p>;
 const check=async()=>{if(checking)return;setChecking(true);setActionError('');setNeedsProject(false);try{setResult(await preDesignedPlanService.currentProjectCompatibility(id))}catch(ex:any){if(ex.response?.status===404&&ex.response?.data?.code==='project_details_required')setNeedsProject(true);else setActionError('Compatibility could not be checked. Please try again.')}finally{setChecking(false)}};
 const usePlan=()=>{if(starting)return;setStarting(true);navigate(`/dashboard/new-project?basePlanId=${id}&mode=use`)};
 const topology=getPlanTopology(plan);
 return <main className="p-6 md:p-10 max-w-7xl mx-auto text-zinc-900 dark:text-white"><Link className="text-indigo-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400" to="/dashboard/plans">← Plan Library</Link><div className="flex flex-wrap justify-between items-end gap-4 my-6"><div><h1 className="text-3xl font-bold">{getCustomerPlanName(plan)}</h1><p className="text-zinc-600 dark:text-zinc-300 mt-2 max-w-2xl">{plan.description}</p><p className="text-xs text-zinc-400 mt-3">Plan reference: {plan.designCode}</p><p className="text-sm text-indigo-700 mt-3 max-w-xl">After this plan is adapted and approved by an architect, you can choose a constructor to build your project.</p></div><div className="flex flex-wrap gap-2"><button disabled={checking} onClick={check} className="border px-4 py-3 rounded-xl focus-visible:ring-4 focus-visible:ring-indigo-200 disabled:opacity-60">{checking?'Checking…':'Check Compatibility'}</button><button disabled={starting} onClick={usePlan} className="bg-indigo-600 text-white px-4 py-3 rounded-xl focus-visible:ring-4 focus-visible:ring-indigo-300 disabled:opacity-60">{starting?'Starting project…':'Use This Plan'}</button></div></div>
 {actionError&&<p role="alert" className="mb-5 p-4 rounded-xl bg-red-50 text-red-800">{actionError}</p>}{needsProject&&<div className="mb-5 p-4 rounded-xl bg-indigo-50 text-indigo-950"><b>Add your project details first</b><p className="mt-1">Add your project details to check whether this plan fits your land and requirements.</p><button onClick={()=>navigate(`/dashboard/new-project?basePlanId=${id}&mode=use`)} className="mt-3 bg-indigo-600 text-white px-4 py-2 rounded-lg">Enter Project Details</button></div>}
 {result&&<div className={`mb-5 p-4 rounded-xl ${result.compatible?'bg-emerald-100 text-emerald-900':'bg-amber-100 text-amber-900'}`}><b>{result.compatible?'✓ Compatible with your project':'Plan needs changes'}</b>{result.landSizePerches!==undefined&&<p className="mt-2">Your land: {result.landSizePerches} perches · Minimum land: {result.minimumLandSizePerches} perches</p>}{[...result.issues,...result.warnings].map(x=><p key={x}>• {x}</p>)}{result.compatible?<button onClick={usePlan} className="mt-3 bg-indigo-600 text-white px-4 py-2 rounded-lg">Use This Plan</button>:<button onClick={()=>navigate(`/dashboard/new-project?basePlanId=${id}&mode=use`)} className="mt-3 border border-amber-700 px-4 py-2 rounded-lg">Edit Project Details</button>}</div>}
 <div className="grid lg:grid-cols-[minmax(0,1fr)_300px] gap-6"><section className="h-[460px] md:h-[620px] min-w-0 rounded-2xl overflow-hidden border border-zinc-200 relative"><div className="absolute z-10 m-3 flex flex-wrap gap-2">{Array.from({length:plan.floorCount},(_,i)=><button key={i} onClick={()=>setFloor(i+1)} className={`px-3 py-1.5 rounded-lg shadow-sm focus-visible:ring-4 focus-visible:ring-indigo-300 ${floor===i+1?'bg-indigo-600 text-white':'bg-white text-zinc-700'}`}>{formatFloorName(i+1)}</button>)}</div><FloorPlanViewer data={plan.layout} floorFilter={floor}/></section><aside className="bg-white dark:bg-gray-900 border rounded-2xl p-5 h-fit"><h2 className="font-bold mb-4">Home Summary</h2>{[['Bedrooms',countLabel(plan.bedrooms,'Bedroom')],['Bathrooms',countLabel(plan.bathrooms,'Bathroom')],['Floors',countLabel(plan.floorCount,'Floor')],['Built-up area',formatArea(plan.totalBuiltUpAreaSqft)],['Layout',topology?formatTopology(topology):'Practical Layout'],['Minimum land',`${plan.minimumLandSizePerches} perches`],['Minimum plot',`${plan.minimumPlotWidthFt??'—'} × ${plan.minimumPlotLengthFt??'—'} ft`],['Site',formatTerrain(plan.suitableTerrain)],['Parking',`${plan.parkingSpaces} ${plan.parkingSpaces===1?'space':'spaces'}`]].map(([k,v])=><div key={k} className="flex justify-between gap-3 border-b py-2 text-sm"><span className="text-zinc-500">{k}</span><b className="text-right">{v}</b></div>)}</aside></div><p className="mt-5 text-sm text-amber-800 bg-amber-50 p-4 rounded-xl">{plan.conceptualDisclaimer}</p></main>
}
